before_install:
- gem install bundler
language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 12
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
  chrome: stable
env:
  global:
  - PGPORT=5433
dist: xenial
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
install:
- bundle install
- nvm install node
- node -v
- npm i -g yarn
- yarn
script:
- bundle exec rails webpacker:compile
- yarn
- bundle exec rails db:{drop,create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: P/rA/JMSMgDUFRZy3PhUyVHcdQ92bFq/M1G4sePqSadlPnMUJQ6iB4dZnxqmLbqY/mJF9xGWTFiUcI/SFyBbafJlge3Gt0kvSDbMgK+3b80yvR43c7Hn/NlhXik+CmGVApNFFRlm+TyYea/EXo7QrHcVU4irPjual0PyxX8N+hdIRHjEppFdS6DKy/alZ2hHFZfcy7aupE7VF8xbtdA8ebulu9dS+HE2uS16huYVYfeVqkvNW9i7EJ131qkGhymMuPdoGUU+TbiPa5n6Iln7U/4qz7a0/nM/QBVaCZ491PyQHyfZzY7siQ6C30zAZ9FaStS9nLHrLp3CMzjOcSGkkPaxgpTYNTEIsUyA84JwI7NMYEwTaRthq7Jpz5t07VfNMNO6kYsdkpe9+UB1Qp0yjCAAvax7Q5sNB+1ih8s2kxzvLwhGy9nW1gUhVXDwuSwUGOt3gp4nFHiLFVB3lproBc3JgAKhByetQKhL+G49gb3ya/pEuTKcoNy40/3+bJQS5Iwtvsv69IjGnq0D4ztzPrCuKtuXfPTZk0ZRpfWBsYHe2kWA6CK0wbcwlmgNaFfz9u8qAcrddbTQi8Yq+J0t48vidIlPDivjGYzGzzWrpQqmdTRp3XNn+UAuCWNhDumbJJzsZyeXoxaYefLFmMpX8GVsQigOEf5kUzMj8K9Ccus=
  app: podsmack
  run: rails db:migrate
