before_install:
  - gem install bundler

language: ruby

rbenv:
- 2.5.3

addons:
  postgresql: 12
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
  chrome: stable

env:
  global:
  - PGPORT=5433

dist: xenial

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rails webpacker:compile
  - yarn
  - bundle exec rails db:reset RAILS_ENV=test
  - bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: adtSKdEYSVpa1qqncZ+d+wwYczo5PGgoYH2SU+Q7K+DU8Yzziy8OVUatOvLFI/We8SnmNUuYAuuEkiKYeK83NRF5cqU5tN5a1AQ2mOtQruI+QK3zah9LxAAx2txHXNivDf0Rlb0rtsani/X9tgXaI2KHN3lmQR2WIeVxlBxBbkGhUYqzxkUtATfA7clc7rTojcEYDrP/Pcpwwqzgw1ZmY3wACVy9BJY5GBB3FdBpuIqkdHYM/FBP3XXdjiKW3heodGkg7TLmJWwoRnq7MEUeFVxNulMg+ZjEzDFc0uraMekcPwrBaqSj3FyJnSqpGk9vbOIThU/HonKDVWUfSsRaOLX3/XOpJa1p+vMpPZfWsgCm/F/ZHqXYZnrn3JXIw5pDtC2GDJ8hFnrWdteGpUWVqR6htjJBTeb+IBsI0afd5+IG0scDcLU3hXRr+W6YlONSnzyhssSvnYGn8Wm4Q2jqhffrM2B6CYBtbhp7DOo/353W9rygnNk8/vVYrKJqOU3QTGDpkAuEjZ6AiXj9qjasgM0mBFX68eaYojZbY2DjK8+WKs7g+QMlcPbjdqq4Uy1gVJT9LbV02UUCfA48cYVwVdiK0+wWgEUNYxLIQmoWjYSVQdHkpeSmBy+N+rF5pWR7OJgzEN1mg7QYp5tPY7zgEgzjCthzl2nqmgxyvzDckQM=
  app: podsmack
  run: rails db:migrate
